apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}-grafana-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app: k8s-mcp-server
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  GRAFANA_URL: {{ .Values.grafana.endpoint | b64enc | quote }}
  GRAFANA_API_KEY: {{ .Values.grafana.apitoken | b64enc | quote }} 