apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}-kubernetes-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app: k8s-mcp-server
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  K8S_URL: {{ .Values.kubernetes.endpoint | b64enc | quote }}
  K8S_TOKEN: {{ .Values.kubernetes.token | b64enc | quote }}
