apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}-openai-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app: k8s-mcp-server
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  AZURE_OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.openai.endpoint | b64enc | quote }}
  AZURE_OPENAI_DEPLOYMENT_NAME: {{ .Values.openai.deploymentName | b64enc | quote }}
  OPENAI_API_VERSION: {{ .Values.openai.apiVersion | b64enc | quote }}
  AZURE_OPENAI_MAX_TOKENS: {{ .Values.openai.maxTokens | toString | b64enc | quote }}
  AZURE_OPENAI_TEMPERATURE: {{ .Values.openai.temperature | toString | b64enc | quote }}
  AZURE_OPENAI_TOP_P: {{ .Values.openai.topP | toString | b64enc | quote }}