apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}-prometheus-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app: k8s-mcp-server
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  PROMETHEUS_ENDPOINT: {{ .Values.prometheus.endpoint | b64enc | quote }} 