{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-mcp-server.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace.name }}
  selector:
    matchLabels:
      {{- include "k8s-mcp-server.selectorLabels" . | nindent 6 }}
{{- end }} 