apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-mcp-server.serviceName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "k8s-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8s-mcp-server.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: https
    port: {{ .Values.service.httpsPort }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: health
    port: {{ .Values.service.healthPort }}
    targetPort: {{ .Values.service.healthPort }}
    protocol: TCP
  {{- if .Values.metrics.enabled }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.port }}
    protocol: TCP
  {{- end }} 